### ISSUE TITLE
Hi, awesome design

### ISSUE THREAD

**Issue by wattsie** [smaseface/BTT-PITFT5-Mount-for-Voron-v2.4#2]
Any chance of original cad, maybe Fusion360 with sketches etc..

Would love to use on a Trident, but need to either move entire mech forward 10mm or more the point where it mounts to the extrusion back 10mm, as the front door interferes with movement.

Thanks in advance.

**Comment by scottmason88** [comment]
I used the stls from the 2.2 repo, and edited them in tinkercad. I don’t have any cad files, sorry

**Comment by wattsie** [comment]
Cool, thanks.
Im not used to tinkercad. would take me ages.
Thanks anyway.
Would love to have been able to use this on the Trident.
Cheers.
