### ISSUE TITLE
CAD File

### ISSUE THREAD

**Issue by dburke555** [smaseface/BTT-PITFT5-Mount-for-Voron-v2.4#3]
Hello!  I was wondering if you would be willing to share the CAD (step/f3d, etc.) for this project?

**Comment by orotecluc** [comment]
Hi,
When installing this mount, I can no longer open the doors because the screen casing is to close to the door handles. Can you please provide CAD files for this mount so we can modify for better performance or customization?

**Comment by scottmason88** [comment]
There is no cad file, I modified things on tinkercad. Haven’t had the time to tinker with printers since kids came along, sorry I probably won’t be able to help here
